services:
  web:
    build: ./web
    container_name: fk_web_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - strapi

  strapi:
    build: ./strapi
    container_name: fk_strapi_app
    restart: always
    ports:
      - "1337:1337"
    env_file:
      - strapi.env
    environment:
    NODE_ENV: development
    volumes:
      - strapi-uploads:/app/public/uploads
      - strapi-tmp:/app/.tmp
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: fk_postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: supersecret
    volumes:
      - strapi-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  strapi-uploads:
  strapi-tmp:
  strapi-db:
